### ISSUE TITLE
Option to disable logging

### ISSUE THREAD

**Issue by sergeevabc** [nref/BrowseRouter#18]
How to prevent BrowseRouter from polluting the disk with logs?
Obviously, we need an option.

**Comment by nref** [comment]
Thanks for the report.
Obviously, I do this for free. I added logging in 0.5.
Please use version 0.4 for now.

Thanks, happy new year.

**Comment by nref** [comment]
Fixed in https://github.com/nref/BrowseRouter/releases/tag/0.7.0.0
