### ISSUE TITLE
Whitespace in URL

### ISSUE THREAD

**Issue by Gankarloo** [nref/BrowseRouter#25]
Unfortunatly BrowseRouter does not work if the URL contains a unescaped whitespace.

For example:
www.example.com/my site/somepath

ends up as:
www.example.com/my

I see two possibilities.
1. always url encode the input string
2. add option in ini file to force url encode for specific url's

**Comment by nref** [comment]
Fixed in https://github.com/nref/BrowseRouter/pull/26
