### ISSUE TITLE
Conflict with defender for endpoint attack surface reduction rule in Outlook

### ISSUE THREAD

**Issue by illgitthat** [nref/BrowseRouter#43]
Sharing this as it seems like this project has had some recent development.

Thank you for your work on this!

I have this error pop up any time I click on a link in Outlook.
![error](https://github.com/user-attachments/assets/7debaaef-ae1b-47d3-8fa1-43fbdade3714)

I found this log of what is causing the error in Microsoft Defender for Endpoint:
![error2](https://github.com/user-attachments/assets/5e1aa6c9-c19b-4410-b5cc-3e6184959099)

More details from the [defender for endpoint docs](https://learn.microsoft.com/en-us/defender-endpoint/attack-surface-reduction-rules-reference#block-office-communication-application-from-creating-child-processes).

I know that this error isn't really the fault of this project, but I'm sharing here in case anyone else has encountered a similar issue and might have found a workaround.

This is related to #35

**Comment by nref** [comment]
Yep, I work on BrowseRouter pretty regularly.

I can try to help with this. Can you send me the BrowseRouter log? You'll find it in `C:\Users\<user>\AppData\Local\BrowseRouter`

**Comment by illgitthat** [comment]
There are no logs related to these links in browserouter. I guess essentially Outlook is not using the default browser program for some reason. This is despite the fact that I had "Default Browser" selected in Outlook options.

For my specific use case, the fix was changing this back to Microsoft Edge in options as that's the browser I happened to want to use.
![image](https://github.com/user-attachments/assets/955799d5-bc3e-41f6-ab05-e75353008181)

That being said, I'm going to go ahead and close out this issue as it seems more like an Outlook bug than an issue with BrowseRouter.

**Comment by nref** [comment]
It looks like Outlook is denied permissions on your machine to launch processes. Edge is probably whitelisted by Microsoft.

It feels like the 90s again in the things Microsoft is doing to give Edge an...edge. For example, it's [not possible](https://kolbi.cz/blog/2024/04/03/userchoice-protection-driver-ucpd-sys/) on the newest builds of Windows 11 for a browser to set itself as the default browser. Of course Edge can.
