### ISSUE TITLE
BrowseRouter Registration missing quotes

### ISSUE THREAD

**Issue by mudnug** [nref/BrowseRouter#63]
Due to the missing quotation marks it appears that other applications may not be able to launch the app when the path contains spaces.

This is stored as the Data in key Computer\HKEY_CLASSES_ROOT\BrowseRouterURL\shell\open\command

**Comment by nref** [comment]
Thanks for the report. I will fix this in the next few days, or accept a PR.

**Comment by mudnug** [comment]
Thank you. I'm still trying to work out what the mechanism is that PowerToys uses to trigger searches (which no longer works with BrowseRouter configured as default) The missing quotes was the first thing I came across. I'm not 100% sure on what the quotes should be and I don't know what specification to consult in relation to that.

**Comment by mudnug** [comment]
When I use
"Z:\Path To\BrowseRouter\BrowseRouter.exe" %1
The browser will launch, but if I use A Search Query in PowerToys, It ends up launching three separate tabs as if each of the words  A Search Query was a separate URL.

**Comment by nref** [comment]
Fixed in the linked PR and released as https://github.com/nref/BrowseRouter/releases/tag/0.13.1. Would you mind to see if it resolve the issue with PowerToys?

![image](https://github.com/user-attachments/assets/43bd7399-5e98-49af-b0bc-8c58df9b4897)

**Comment by mudnug** [comment]
What's the procedure for me to test this? Would I need to unregister and then register again and then make sure it is set as default in Windows settings?

**Comment by nref** [comment]
Good question. Just double-click the exe and it will update the existing registry keys with the new quoted path.

**Comment by mudnug** [comment]
Following your steps the app did update the registry.

This breaks double clicking on .URL files for me (as well as PowerToys not working).

As I mention above, 
When I use "Z:\Path To\BrowseRouter\BrowseRouter.exe" %1 the browser will launch
but with the new  "Z:\Path To\BrowseRouter\BrowseRouter.exe %1" it will not

I do not know what the specification is for these registry keys, however.

**Comment by nref** [comment]
Thanks for the quick feedback. You're right, I put the quote in the wrong spot - I will fix this tomorrow.

**Comment by nref** [comment]
Could you please try https://github.com/nref/BrowseRouter/releases/tag/0.13.2? Thanks

**Comment by mudnug** [comment]
I ran the tagged exe several times and it looks like it's putting the expected value in the registry now. Nothing broke.

I will rename https://github.com/nref/BrowseRouter/issues/55 so it is more clear what that request is about

**Comment by nref** [comment]
Thanks for your help testing the fix!
